"""Command-line execution helpers for the notebook pipeline."""

from __future__ import annotations

import pandas as pd

from framework_v7.data_access import ProjectData, load_project_data

from . import (
    evaluation,
    experiment_design,
    interpretation,
    layer_extraction,
    layer_framework,
    machine_learning,
    ml_preparation,
    model_governance,
    modeling,
)


def run_pipeline_summary(data: ProjectData | None = None) -> pd.DataFrame:
    """Execute a lightweight validation of modular notebook artifacts.

    This function does not train models or rewrite data. It verifies that the
    modular pipeline can load existing artifacts and produce stage-level
    summaries from the same outputs generated by the notebooks.

    Args:
        data (ProjectData | None): Optional preloaded project data. When
            ``None``, the function calls ``load_project_data``.

    Returns:
        pd.DataFrame: Summary table with ``Etapa``, ``Modulo`` and
        ``Resultado`` columns.
    """

    data = data or load_project_data()
    rows = []

    layer_summary = layer_extraction.layer_execution_summary()
    if not layer_summary.empty:
        rows.append(
            {
                "Etapa": "C01-C07",
                "Modulo": "layer_extraction.py",
                "Resultado": (
                    f"{int(layer_summary['Disponible'].sum())}/{len(layer_summary)} capas "
                    f"con {int(layer_summary['Artefactos_MASTER'].sum())} artefactos master"
                ),
            }
        )

    framework_notebooks = layer_framework.framework_notebook_inventory()
    framework_outputs = layer_framework.summarize_layer_framework_outputs()
    if not framework_notebooks.empty:
        rows.append(
            {
                "Etapa": "C01-C07",
                "Modulo": "layer_framework.py",
                "Resultado": (
                    f"{len(framework_notebooks)} notebooks framework y "
                    f"{int(framework_outputs['Disponible'].sum())}/{len(framework_outputs)} "
                    "datasets framework disponibles"
                ),
            }
        )

    design_summary = experiment_design.design_summary(data.experiment_design)
    rows.append(
        {
            "Etapa": "DISENO_EXPERIMENTAL",
            "Modulo": "experiment_design.py",
            "Resultado": f"{int(design_summary['Disponible'].sum())}/{len(design_summary)} artefactos",
        }
    )

    target = data.meta.get("Variable Objetivo", "irca")
    if not data.master.empty:
        rows.append(
            {
                "Etapa": "C08-C09",
                "Modulo": "integration.py / feature_engineering.py",
                "Resultado": f"{data.master.shape[0]} filas x {data.master.shape[1]} columnas maestro",
            }
        )

    if not data.ml_dataset.empty and target in data.ml_dataset.columns:
        diagnostic = ml_preparation.modeling_dataset_diagnostic(data.ml_dataset, target)
        rows.append(
            {
                "Etapa": "C12",
                "Modulo": "ml_preparation.py",
                "Resultado": (
                    f"{int(diagnostic.loc[diagnostic['Indicador'] == 'predictoras_numericas', 'Valor'].iloc[0])} "
                    "predictoras numericas"
                ),
            }
        )
        transform = machine_learning.transformation_diagnostic(data.ml_dataset)
        rows.append(
            {
                "Etapa": "C13",
                "Modulo": "machine_learning.py",
                "Resultado": (
                    f"{int(transform.loc[transform['Indicador'] == 'variables_constantes', 'Valor'].iloc[0])} "
                    "variables constantes"
                ),
            }
        )

    if not data.model_diagnostic.empty:
        rows.append(
            {
                "Etapa": "C14-C15",
                "Modulo": "modeling.py / evaluation.py",
                "Resultado": f"{len(data.model_diagnostic)} indicadores de diagnostico Exp01",
            }
        )

    ml_summary = machine_learning.summarize_ml_experiments()
    if not ml_summary.empty:
        rows.append(
            {
                "Etapa": "C13",
                "Modulo": "machine_learning.py",
                "Resultado": f"{len(ml_summary)} experimentos con artefactos de transformacion",
            }
        )

    modeling_summary = modeling.summarize_modeling_experiments()
    if not modeling_summary.empty:
        rows.append(
            {
                "Etapa": "C14",
                "Modulo": "modeling.py",
                "Resultado": f"{len(modeling_summary)} experimentos con artefactos de modelado",
            }
        )

    evaluation_summary = evaluation.summarize_evaluation_experiments()
    if not evaluation_summary.empty:
        rows.append(
            {
                "Etapa": "C15",
                "Modulo": "evaluation.py",
                "Resultado": f"{len(evaluation_summary)} experimentos con predicciones exportadas",
            }
        )

    interpretation_summary = interpretation.summarize_interpretation_experiments()
    if not interpretation_summary.empty:
        rows.append(
            {
                "Etapa": "C16",
                "Modulo": "interpretation.py",
                "Resultado": f"{len(interpretation_summary)} resumenes de interpretacion consolidados",
            }
        )

    governance_summary = model_governance.governance_summary()
    if not governance_summary.empty:
        governed_models = governance_summary.loc[
            governance_summary["Indicador"] == "modelos_gobernados",
            "Valor",
        ].iloc[0]
        governed_risks = governance_summary.loc[
            governance_summary["Indicador"] == "riesgos_controlados",
            "Valor",
        ].iloc[0]
        rows.append(
            {
                "Etapa": "C17",
                "Modulo": "model_governance.py",
                "Resultado": f"{governed_models} modelos gobernados y {governed_risks} riesgos controlados",
            }
        )

    return pd.DataFrame(rows)


def print_pipeline_summary(summary: pd.DataFrame) -> None:
    """Print pipeline summary rows to stdout.

    Args:
        summary (pd.DataFrame): Output from ``run_pipeline_summary``.

    Returns:
        None: The function prints to stdout.
    """

    print("PIPELINE MODULAR DE NOTEBOOKS")
    print("=" * 72)
    for row in summary.to_dict("records"):
        print(f"{row['Etapa']}: {row['Modulo']} -> {row['Resultado']}")


def main() -> None:
    """Run notebook-pipeline validation from the command line.

    Args:
        None.

    Returns:
        None: The function prints the pipeline summary to stdout.
    """

    print_pipeline_summary(run_pipeline_summary())


if __name__ == "__main__":
    main()
